### PR TITLE
Image improvements

### PR DESCRIPTION
**Pull request by NeroAzure**
- ~~update base image to version 8.1~~
- fix composer installation
- remove duplicated ~~and outdated~~ extension installations
- reorder layers for better caching
- install iconv in the main install statement

### CODE REVIEW

**Comment by NeroAzure** [comment]
Some of the improvements could be done in separate PRs without the update to 8.1, if wanted.

**Comment by SebastianMueller87** [comment]
I would suggest to split these changes into two separate pull requests. (PHP8.1 & other changes)

**Comment by NeroAzure** [comment]
Removed the update of the php image version, to allow for a 8.0 release with these improvements. Dependabot will handle the update to 8.1.

**Review by SebastianMueller87 — COMMENTED** [review]
👍

**Pull request merged**
